# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-18 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'ongoing'), (2, 'complete')], default=0)),
                ('request_location_lat', models.DecimalField(decimal_places=11, max_digits=15)),
                ('request_location_long', models.DecimalField(decimal_places=11, max_digits=15)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverApp.Customer')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DriverApp.Driver')),
            ],
        ),
    ]
