# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-18 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApp', '0002_auto_20171218_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
