# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriverApp', '0004_auto_20171219_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_location_lat',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_location_long',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True),
        ),
    ]
